# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-12-22 16:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fizzbuzz',
            name='message',
            field=models.TextField(),
        ),
    ]
